FROM alpine:latest

WORKDIR /config

COPY docker-compose.yml .
COPY requirements.txt .
COPY dags/ ./dags/
COPY scripts/ ./scripts/
COPY models/ ./models/
COPY api/ ./api/
COPY frontend/ ./frontend/

CMD ["cp", "-r", "/config/.", "/deployment/"]